"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-fallback-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Required for django-allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
    # Core app
    'toddlecross',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Add AccountMiddleware for django-allauth
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# This directory is where Django will collect all our static files (like CSS and JS)
# when we run the python manage.py collectstatic command.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# This setting tells WhiteNoise to gzip and cache our static files in production.
# It makes the website load faster by compressing files.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Authentication Settings (django-allauth)

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Django-allauth configurations
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Set to mandatory or optional for production

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APPS': [
            {
                'client_id': os.getenv('GOOGLE_CLIENT_ID', ''),
                'secret': os.getenv('GOOGLE_CLIENT_SECRET', ''),
                'key': ''
            }
        ],
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'allauth': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}

# LTI 1.3 Configurations
LTI_KEYS_DIR = BASE_DIR / 'config' / 'lti_keys'
LTI_PRIVATE_KEY_FILE = LTI_KEYS_DIR / 'private.key'
LTI_PUBLIC_KEY_FILE = LTI_KEYS_DIR / 'public.key'

TODDLE_LTI_ISSUER = os.getenv('TODDLE_LTI_ISSUER_URL', '')
TODDLE_LTI_CLIENT_ID = os.getenv('TODDLE_LTI_CLIENT_ID', '')
TODDLE_LTI_LOGIN_URL = os.getenv('TODDLE_LTI_LOGIN_URL', '')
TODDLE_LTI_KEYSET_URL = os.getenv('TODDLE_LTI_KEYSET_URL', '')
TODDLE_LTI_TOKEN_URL = os.getenv('TODDLE_LTI_TOKEN_URL', '')
TODDLE_LTI_DEPLOYMENT_ID = os.getenv('TODDLE_LTI_DEPLOYMENT_ID', '')

# These settings tell our website the default administrator credentials.
# We read these values from a secret .env file.
# If they are not found in the .env file, we fall back to safe default values.
# The username is used to log in.
SUPERUSER_USERNAME = os.getenv('SUPERUSER_USERNAME', 'admin')
# The email address for the administrator.
SUPERUSER_EMAIL = os.getenv('SUPERUSER_EMAIL', 'admin@example.com')
# The password the administrator will use to log in.
SUPERUSER_PASSWORD = os.getenv('SUPERUSER_PASSWORD', 'adminpassword')

# Toddleapp core API configuration settings.
# We read these values from the environment variables to keep our API keys secure.
TODDLE_API_BASE_URL = os.getenv('TODDLE_API_BASE_URL', 'https://ap-southeast-1-production-apis.toddleapp.com/')
TODDLE_API_KEY = os.getenv('TODDLE_API_KEY', '')

# Veracross OAuth2 and API settings.
# We load the base endpoint, OAuth authentication URL, client ID, and secret.
VERACROSS_API_BASE_URL = os.getenv('VERACROSS_API_BASE_URL', '')
VERACROSS_TOKEN_URL = os.getenv('VERACROSS_TOKEN_URL', '')
VERACROSS_CLIENT_ID = os.getenv('VERACROSS_CLIENT_ID', '')
VERACROSS_CLIENT_SECRET = os.getenv('VERACROSS_CLIENT_SECRET', '')

# Production security settings.
# These headers tell Django how to handle SSL/HTTPS redirects and secure cookies.
# The proxy SSL header tells Django to trust HTTPS requests forwarded by a load balancer/proxy.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# If set to True, all non-HTTPS requests are redirected to HTTPS.
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'
# This ensures session cookies are only sent over secure HTTPS connections.
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'
# This ensures CSRF security cookies are only sent over secure HTTPS connections.
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False') == 'True'


