# Generated by Django 5.2.15 on 2026-06-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toddlecross', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncjob',
            name='sync_type',
            field=models.CharField(choices=[('students', 'Students Only'), ('teachers', 'Teachers Only'), ('both', 'Complete Sync')], default='both', max_length=20),
        ),
    ]
