# Generated by Django 5.2.15 on 2026-06-27 17:12

import toddlecross.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toddlecross', '0002_syncjob_sync_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Sync Schedule', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('cron_expression', models.CharField(default='0 * * * *', help_text='Standard 5-field cron expression: minute hour day-of-month month day-of-week (e.g., "*/15 * * * *" or "0 2 * * *")', max_length=100, validators=[toddlecross.models.validate_cron_expression])),
                ('sync_type', models.CharField(choices=[('students', 'Students Only'), ('teachers', 'Teachers Only'), ('both', 'Complete Sync')], default='both', max_length=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
